### ISSUE TITLE
Display the network that the game will be on 

### ISSUE THREAD

**Issue by MrLuisAmador** [xxhomey19/nba-go#59]
Does this display the network that the game will be on? I search Google to see what games will be on for the week and also on what network they will be live on. I don't have NBATV. I only watch games on ESPN or TNT so that's what I'm normally searching Google for.

**Comment by xxhomey19** [comment]
Hi @MrLuisAmador 
The API I used does have this information, so this feature should be easy to accomplish. I’m busy these weeks, so PR is welcomed!

**Comment by justinrsmith** [comment]
Is this something desired on the Schedule listing or when an actual game is selcted? Or both? I may try to tackle this.

@MrLuisAmador @xxhomey19

**Comment by xxhomey19** [comment]
I think on game schedule would be better.

**Comment by justinrsmith** [comment]
Cool I will look at doing that. I did add it in the game preview just as I was playing around getting familiar with the codebase. Just in case you want to see what I was thinking. I won't keep it in for now though.

<img width="349" alt="screen shot 2018-01-26 at 10 46 45 am" src="https://user-images.githubusercontent.com/3534132/35450699-64a2426c-0286-11e8-9956-7ed979ae2b4a.png">

**Comment by xxhomey19** [comment]
That's cool. For game preview, I think keep the network information there would be great. 
So, this information would be shown in two place. 
1. game schedule
2. game preview

Is that okey?

**Comment by justinrsmith** [comment]
Sounds good to me. I will keep you posted.

**Comment by justinrsmith** [comment]
Still working on implementing it for the game schedule view. Right now it will always show the broadcast by default. The broadcast names can get quite lengthy and almost double the size of the schedule table (see attached). I am thinking maybe it should be an option the user can provide. What do you think? @xxhomey19 

<img width="1282" alt="screen shot 2018-01-29 at 7 26 32 pm" src="https://user-images.githubusercontent.com/3534132/35543820-dffb316e-052c-11e8-8c27-1913a86ed496.png">

**Comment by xxhomey19** [comment]
Yeah, that's a bit too lengthy. Providing a option to show these will be great!
So does showing these lengthy information in preview page look okay?

**Comment by justinrsmith** [comment]
Game preview looks ok I think since there is a fair amount of room to work with there (see attached). I am working on getting it set up for live game and completed game when I have some time. I will show you when I have that ready.
<img width="1038" alt="screen shot 2018-01-30 at 6 56 31 pm" src="https://user-images.githubusercontent.com/3534132/35599675-91ce78b6-05ef-11e8-8371-8d6185481cd2.png">

**Comment by MrLuisAmador** [comment]
@justinrsmith 

This is great! I continuously review the TV network through Google Search at least every other day so this feature is very useful to me and I'm sure others.

**Comment by justinrsmith** [comment]
Just wanted to check in on this. Broke out what I have done so far below. One thing to note is how I handled national broadcasts vs local broadcasts. What I do is always use the local broadcast network but if there is no local broadcast network then I check the national broadcast network and if there is one I list that. If there are neither local or national for some reason I list N/A as the broadcast. From what I see there will never be a scenario for N/A being listed as broadcast network. So really I just have some code clean up I want to do since I am sort of new to using javascript in this way. Once I have that complete I will submit a pull requests. Let me know any thoughts/concerns/changes to the below you may have. Thanks!

### Schedule
I add a command line options to go with the `game/g` command that is either `-n` or `--networks` that will have the broadcast networks show on the schedule (see below screenshot).
![screen shot 2018-02-08 at 6 38 07 pm](https://user-images.githubusercontent.com/3534132/36005841-3a152dba-0cff-11e8-88fb-1d9f57567780.png)

### Live Game
When selecting a live game the broadcast network will show below each respective team record (see below screenshot).
![screen shot 2018-02-08 at 6 40 19 pm](https://user-images.githubusercontent.com/3534132/36005934-b7abff38-0cff-11e8-97f1-637d22737fc1.png)

### Game Preview
When previewing a game the home/away broadcast will show below arena/city information (see below screenshots).
![screen shot 2018-02-08 at 6 43 46 pm](https://user-images.githubusercontent.com/3534132/36006148-da6a5a46-0d00-11e8-8564-9bbbd6fb5e0e.png)
![screen shot 2018-02-08 at 6 44 01 pm](https://user-images.githubusercontent.com/3534132/36006149-db5388ce-0d00-11e8-8df4-d59b61592418.png)

### Completed Game
When looking at a completed game the broadcast networks will show below the arena/city information. I am not sure if broadcast network information is necessary for a completed game? (see below screenshot).
![screen shot 2018-02-08 at 6 50 33 pm](https://user-images.githubusercontent.com/3534132/36006193-16b2efcc-0d01-11e8-84ae-49993d1b0de9.png)

**Comment by xxhomey19** [comment]
That's really awesome!!! Thanks for your contribution.
I have only one thought. The location of network in LIVE game is just a little bit strange. I prefer it 's placed below the stadium or above game date. Will this cause any inconvenience?

**Comment by justinrsmith** [comment]
Nope I do not think that will be a problem at all. I will look into doing that.

**Comment by justinrsmith** [comment]
Went ahead and made that change for the LIVE game as seen in the two screenshots below. Let me know what you think. If it looks good to you then I am going to work on some code cleanup and should have a pull request ready in a couple days.

<img width="1402" alt="screen shot 2018-02-09 at 9 58 01 am" src="https://user-images.githubusercontent.com/3534132/36036796-66d9fdf4-0d80-11e8-848c-5c4cc04817c3.png">
<img width="1416" alt="screen shot 2018-02-09 at 9 58 30 am" src="https://user-images.githubusercontent.com/3534132/36036797-66edc974-0d80-11e8-9c2c-c4655069f145.png">

**Comment by xxhomey19** [comment]
It looks great! Perfect!

**Comment by MrLuisAmador** [comment]
@xxhomey19 @justinrsmith 

I'm testing the area "which game do you want to watch" and I'm not seeing the broadcasts channel like in the above image demo.

![testing](https://user-images.githubusercontent.com/6766589/36522801-87a059de-176c-11e8-9d24-ee95d08a90ef.png)

**Comment by justinrsmith** [comment]
@MrLuisAmador glad you got it. I agree with @xxhomey19 that it should be option purely due to how wide it can make the table depending on screen/terminal size it could cause some issues. We can always revisit later if that is something that is decided it should always show.

**Comment by MrLuisAmador** [comment]
@justinrsmith, thank you for adding this feature in the first place. Wish I could contribute but I just can't wrap my head around the code. I'll keep messing around until I get a grip on how the source code works.

@xxhomey19 Thank you too for such a great cli tool.

**Comment by justinrsmith** [comment]
@MrLuisAmador You are welcome. Ya it took me a bit of time to get my mind around it too. Definitely was a learning experience!
